USE db_rfp102;

#DROP TABLE IF EXISTS rwlUser, rwlPage, rwlEntry, rwlHistory, rwlDifference;
DROP TABLE IF EXISTS rwlHistory, rwlEntry, rwlUser;

CREATE TABLE rwlUser
(
	id		INTEGER	AUTO_INCREMENT	NOT NULL,
	un		VARCHAR(20)				NOT NULL,
	epw		BLOB				NOT NULL,	#	DEFAULT ENCRYPT('abc123','rp'),
	level		INTEGER				NOT NULL	DEFAULT 0,

	email		VARCHAR(100)			NOT NULL,
	
	PRIMARY KEY(id),
	UNIQUE(un)
) type=InnoDB;

#CREATE TABLE rwlPage
#(
#	id		INTEGER	AUTO_INCREMENT	NOT NULL,
#	name		VARCHAR(255) 			NOT NULL,
#
#	PRIMARY KEY(id),
#	UNIQUE(name)
#) type=InnoDB;


##
# An entry containing the 
##
CREATE TABLE rwlEntry
(
	id		INTEGER	AUTO_INCREMENT	NOT NULL,
	page		VARCHAR(255)			NOT NULL,
	content	TEXT					NOT NULL,
#	type		ENUM('',''),
	level		INTEGER,

	creator	INTEGER				NOT NULL,
	created	DATETIME				NOT NULL,
	cip		VARCHAR(50),

	editor	INTEGER				NOT NULL,
	edited	DATETIME				NOT NULL,
	eip		VARCHAR(50),

	PRIMARY KEY(id),
	UNIQUE(page,level)#,

#	FOREIGN KEY(page) REFERENCES rwlPage(id),
#	FOREIGN KEY(creator) REFERENCES rwlUser(id),
#	FOREIGN KEY(editor) REFERENCES rwlUser(id)
) type=InnoDB;


##
# Groups difference strings into historical revisions.
# Update: Stores all revision strings as an array PHP
# code string.
##
CREATE TABLE rwlHistory
(
	id		INTEGER	AUTO_INCREMENT	NOT NULL,
	entry		INTEGER				NOT NULL,
	diff		TEXT					NOT NULL,

	editor	INTEGER				NOT NULL,
	edited	DATETIME				NOT NULL,
	eip		VARCHAR(50),

	PRIMARY KEY(id),

	FOREIGN KEY(entry) REFERENCES rwlEntry(id)
) type=InnoDB;


##
# Stores all difference strings generated by the diff code.
# Linked to a particular historical revision.
##
#CREATE TABLE rwlDifference
#(
#	id	INTEGER	AUTO_INCREMENT	NOT NULL,
#	hist	INTEGER	NOT NULL,
#	diff	VARCHAR(255)
#) type=InnoDB;


INSERT INTO rwlUser(un, level, epw) VALUES('rprince', 1, ENCRYPT('maggot','rp'));
#INSERT INTO rwlPage(name) VALUES('Main'),('Test');
#INSERT INTO rwlEntry(page,content,level,creator,created,editor,edited) VALUES('Test','Hello there!  This is a test page...',0,1,NOW(),1,NOW());